export const HAIR_CLIPPERS = [
  {
    id: 1,
    name: 'Hair Clipper 1',
    image: 'hairClipper/1',
    sound: 'hairclippersound1.mp3',
    needVip: false,
  },
  {
    id: 2,
    name: 'Hair Clipper 2',
    image: 'hairClipper/2',
    sound: 'hairclippersound2.mp3',
    needVip: false,
  },
  {
    id: 3,
    name: 'Hair Clipper 3',
    image: 'hairClipper/3',
    sound: 'hairclippersound3.mp3',
    needVip: false,
  },
  {
    id: 4,
    name: 'Hair Clipper 4',
    image: 'hairClipper/4',
    sound: 'hairclippersound4.mp3',
    needVip: true,
  },
  {
    id: 5,
    name: 'Hair Clipper 5',
    image: 'hairClipper/5',
    sound: 'hairclippersound5.mp3',
    needVip: true,
  },
  {
    id: 6,
    name: 'Hair Clipper 6',
    image: 'hairClipper/6',
    sound: 'hairclippersound6.mp3',
    needVip: true,
  },
  {
    id: 7,
    name: 'Hair Clipper 7',
    image: 'hairClipper/7',
    sound: 'hairclippersound7.mp3',
    needVip: true,
  },
  {
    id: 8,
    name: 'Hair Clipper 8',
    image: 'hairClipper/8',
    sound: 'hairclippersound8.mp3',
    needVip: true,
  },
  {
    id: 9,
    name: 'Hair Clipper 9',
    image: 'hairClipper/9',
    sound: 'hairclippersound9.mp3',
    needVip: true,
  },
  {
    id: 10,
    name: 'Hair Clipper 10',
    image: 'hairClipper/10',
    sound: 'hairclippersound10.mp3',
    needVip: true,
  },
];

export const HAIR_DRYERS = [
  {
    id: 1,
    name: 'Hair Dryer 1',
    image: 'hairDry/1',
    sound: 'hairdryersound1.mp3',
    needVip: false,
  },
  {
    id: 2,
    name: 'Hair Dryer 2',
    image: 'hairDry/2',
    sound: 'hairdryersound2.mp3',
    needVip: false,
  },
  {
    id: 3,
    name: 'Hair Dryer 3',
    image: 'hairDry/3',
    sound: 'hairdryersound3.mp3',
    needVip: false,
  },
  {
    id: 4,
    name: 'Hair Dryer 4',
    image: 'hairDry/4',
    sound: 'hairdryersound4.mp3',
    needVip: true,
  },
  {
    id: 5,
    name: 'Hair Dryer 5',
    image: 'hairDry/5',
    sound: 'hairdryersound5.mp3',
    needVip: true,
  },
  {
    id: 6,
    name: 'Hair Dryer 6',
    image: 'hairDry/6',
    sound: 'hairdryersound6.mp3',
    needVip: true,
  },
  {
    id: 7,
    name: 'Hair Dryer 7',
    image: 'hairDry/7',
    sound: 'hairdryersound7.mp3',
    needVip: true,
  },
  {
    id: 8,
    name: 'Hair Dryer 8',
    image: 'hairDry/8',
    sound: 'hairdryersound8.mp3',
    needVip: true,
  },
  {
    id: 9,
    name: 'Hair Dryer 9',
    image: 'hairDry/9',
    sound: 'hairdryersound9.mp3',
    needVip: true,
  },
  {
    id: 10,
    name: 'Hair Dryer 10',
    image: 'hairDry/10',
    sound: 'hairdryersound10.mp3',
    needVip: true,
  },
];

export const FUNNY_SOUNDS = [
  {
    id: 1,
    name: 'Funny Sound 1',
    emoji: '🐕',
    sound: 'funsound1.mp3',
    needVip: false,
  },
  {
    id: 2,
    name: 'Funny Sound 2',
    emoji: '🐱',
    sound: 'funsound2.mp3',
    needVip: false,
  },
  {
    id: 3,
    name: 'Funny Sound 3',
    emoji: '💨',
    sound: 'funsound3.mp3',
    needVip: false,
  },
  {
    id: 4,
    name: 'Funny Sound 4',
    emoji: '🤡',
    sound: 'funsound4.mp3',
    needVip: true,
  },
  {
    id: 5,
    name: 'Funny Sound 5',
    emoji: '🐄',
    sound: 'funsound5.mp3',
    needVip: true,
  },
  {
    id: 6,
    name: 'Funny Sound 6',
    emoji: '🦆',
    sound: 'funsound6.mp3',
    needVip: true,
  },
  {
    id: 7,
    name: 'Funny Sound 7',
    emoji: '🐸',
    sound: 'funsound7.mp3',
    needVip: true,
  },
  {
    id: 8,
    name: 'Funny Sound 8',
    emoji: '🐷',
    sound: 'funsound8.mp3',
    needVip: true,
  },
  {
    id: 9,
    name: 'Funny Sound 9',
    emoji: '🐯',
    sound: 'funsound9.mp3',
    needVip: true,
  },
  {
    id: 10,
    name: 'Funny Sound 10',
    emoji: '🐵',
    sound: 'funsound10.mp3',
    needVip: true,
  },
];